# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ef1459f36816755a1627ad5515da986d47a471df2fd6270e07df9a7ad9503f92122bf2bde3b84f7b5ed734c77242b95d13ca2a8044363ee53e005dffc49c3f6

test:
  secret_key_base: c878afe318d7b58bd5a05ef5aec5f4a70b50b1b003d003575f41a6b83414fe6ca222388763eb87b84ff4d0baa81a790d27cc269d64e019ff77fb4393ca1a23d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
